---

- name: Create group
  group:
    name: '{{ taskserver_group }}'
    state: present

- name: Create User    
  user:
    name: '{{ taskserver_user }}'
    group: '{{ taskserver_group }}'
    state: present

- name: install task from apt
  apt:
    name: task
    update_cache: yes
